apiVersion: apps/v1
kind: Deployment
metadata:
  name: salutations-deployment
  labels:
    app: salutations
spec:
  replicas: 3
  selector:
    matchLabels:
      app: salutations
  template:
    metadata:
      labels:
        app: salutations
    spec:
      containers:
      - name: salutations-globe
        image: justatad/salutations_globe
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: salutations-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: salutations.ucci.uk.
spec:
  type: LoadBalancer
  selector:
    app: salutations
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
